import { getRecentBlogArticles } from '$lib/server/services/blogArticles';
import type { Load } from '@sveltejs/kit';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 60,
	}
};

export const load: Load = async ({ fetch }) => {
	const articles = await getRecentBlogArticles(fetch);
	return { articles };
};
