import type { Load } from '@sveltejs/kit';
import { getProjects, getProjectTypes } from '$lib/server/services/projects';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 60,
	}
};

export const load: Load = async ({ fetch }) => {
	const projects = await getProjects(fetch);
	const projectTypes = await getProjectTypes(fetch);
	return { projects, projectTypes };
};
