import type { Load } from '@sveltejs/kit';
import { getBlogArticleBySlug } from '$lib/server/services/blogArticles';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 60,
	}
};

export const load: Load = async ({ fetch, params }) => {
	const { slug } = params;
	if (!slug) {
		return null;
	}
	const data = await getBlogArticleBySlug(fetch, slug);
	return data;
};
